### ISSUE TITLE
Wrong type of Cvar value will cause error

### ISSUE THREAD

**Issue by 4512369781** [smilz0/Left4Lib#5]
should use `Convars.GetFloat()` replace `Convars.GetStr()` in **::Left4Utils.GetMaxAmmo**

if a Cvar been set to wrong type value, 'Convars.GetStr("CVAR").tointeger();' will throw error: **AN ERROR HAS OCCURED [cannot convert the string]**.

**Comment by smilz0** [comment]
Sorry man i completely missed this one.
