### ISSUE TITLE
Server crash: KERNELBASE.dll + 0x14b472

### ISSUE THREAD

**Issue by SefoNotasi** [smilz0/Left4Lib#7]
As soon as I install this script together with SourceMod plugin [Restart Empty Server](https://forums.alliedmods.net/showthread.php?t=315367) - the server starts to crash instantly with the following error (Accelerator): **KERNELBASE.dll + 0x14b472**

Here is an example of such crash log: https://crash.limetech.org/ndrwjfso6yol

The crash happens when there are no players on the server and the plugin restarts it with a map change.

There are no errors in SourceMod logs. Here are the last lines of the server console before the crash:
1045	14.628522	L 11/23/2024 - 17:26:36: Changing map to: c11m2_offices... Reason: Server is restarted
1046	14.632197	[SM] Changing map to c11m2_offices...
1047	14.633172	L 11/23/2024 - 17:26:36: [basecommands.smx] "Console<0><Console><Console>" changed map to "c11m2_offices" (input "c11m2_offices")
1048	14.635760	Connection to Steam servers successful.
1049	14.758476	VAC secure mode is activated.
1050	20.504985	L 11/23/2024 - 17:26:42: [SM] Changed map to "c11m2_offices"
1051	20.545715	Server is hibernating
1052	20.546792	ConVarRef test_progression_loop doesn't point to an existing ConVar

I'm trying this on Windows, with the latest versions of the scripts (Left 4 Lib, Left 4 Bots 2) from the workshop. sourcemod-1.12.0-git7167

I also tried installing this script and plugin on a clean server without any other plugins or scripts. As soon as the plugin AND this script are on the server, then the server starts crashing constantly when the plugin changes the map.

**Comment by smilz0** [comment]
Hey. I already answered on workshop, i'm gonna copy paste it here:
sounds like a known bug of the dedicated server that happens when you set the sb_all_bot_game cvar to 1.
If you want you can try the dev version of the addon you can find on github:
[https://github.com/smilz0/Left4Bots/blob/main/out/Left4Bots2.vpk](https://github.com/smilz0/Left4Bots/blob/main/out/Left4Bots2.vpk)
and also Left 4 Lib:
[https://github.com/smilz0/Left4Bots/blob/main/out/Left4Bots2.vpk](https://github.com/smilz0/Left4Lib/blob/main/out/Left4Lib.vpk)
Remove the sb_all_bot_game line from convars.txt and also make sure that no other addon/plugin sets that.

**Comment by SefoNotasi** [comment]
> sounds like a known bug of the dedicated server that happens when you set the sb_all_bot_game cvar to 1

Thank you for your quick response and help.
You were right, it's about those commands: **allow_all_bot_survivor_team 1** and **sb_all_bot_game 1**. They were written in my **server.cfg** and, apparently, somehow conflicted with the same commands in the **L4B2 convars.txt**. As soon as I removed these 2 commands from **convars.txt** - the server stopped crashing.

I also tried dev versions of L4B2 + L4L and they didn't help, the server kept crashing instantly on startup and map change. Until I removed **allow_all_bot_survivor_team 1** and **sb_all_bot_game 1** from **L4B2 convars.txt** and left **sm_cvar sb_all_bot_game 1** + **sm_cvar allow_all_bot_survivor_team 1** in my **server.cfg**.

Looks like some kind of weird config conflict, idk.
